baseURL = "https://example.com/"
title = "Compose Docs"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = [
  "github.com/cellebyte/compose",
] # edit this if you'ld rather use a fork of this repo
# theme = "compose"
enableGitInfo = true

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

# disableKinds = ["taxonomy"]

[outputs]
home = ["HTML", "RSS", "JSON"]
